services:
  backend:
    build:
      context: ./docker_backend
    ports:
      - "4000:4000"
    #env_file:
      #- .env
    networks:
      - app-network

  frontend:
    build:
      context: ./docker_frontend
    ports:
      - "3000:80"
    #env_file:
      #- .env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge